In [109]:
import string
import io
import numpy as np

In [110]:
A = np.array([[2,4,7],[9,2,8]])
B = np.array([[2,4],[1,5],[7,6]])
E = np.array([2,7,9])
F = np.array([2,7,9])

In [111]:
C = np.dot(A,B)
D = np.dot(A[1:],B)
G = E.dot(np.array([F]).T)
H = E.reshape(3,1).dot([F])

In [112]:
print(C)
print(D)
print(G)
print(H)

[[57 70]
 [76 94]]
[[76 94]]
[134]
[[ 4 14 18]
 [14 49 63]
 [18 63 81]]
